name: test-plugin
on: [push, pull_request]
jobs:
  lint-python:
    name: lint-python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install flake8
      run: |
        pip install flake8
    - name: Lint python with flake8
      run: |
        flake8 . --max-complexity=10 --statistics
  test:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install packages
      run: |
        pip install .
        pip install pytest
    - name: Test packages
      run: |
        pytest tests
