name: test-plugin
on: [push, pull_request]
jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install packages
      run: |
        pip install .
        pip install pytest
    - name: Test packages
      run: |
        pytest tests
